### ISSUE TITLE
Scam Report - [Transaction ID/DApp/URL/NFT] another 19..

### ISSUE THREAD

**Issue by bnchk** [adabox-aio/cardano-shield#16]
Goofy Gophers Free Mint Key
f31f5009888e53a37dd024d94f295b0e2ad4f098db9769a0540dc26e
ggmcnft.com
https://pool.pm/asset15qxd9nvgnfealwdmrmkjpflwvdkpw3mxx9727f

JellyCubes NFT Free Mint Key
b6c2ae3f0379d9682e641e930cd21acfef2e29ccb8a3170230335fd9
blockinvestmentgroup.org
https://pool.pm/asset168p32v05c9ma63374rnxwqts6vq8z66ged2rr6

CORNUCOPIAS NFT Free MINT KEY V2
29c4a94e0db116a54d47abd7f275c0134ab2ecbfaccaa2a29f051543
cornucopiasnfts.com
https://pool.pm/asset1lzd8gj7y0ev4jhml3vv5la2p9ekjstc8ja6xu6

Derpbirds NFT Free Mint Key
3f0a916d0a652364d29f58537277a767bf5cfac651ef6856770831a1
derpbirds.org
https://pool.pm/asset16x2kxagrry5u5w5xrgvmpzdnfru3ypatj7k2z0

BossCat Rocket Club NFT Mint Key
985ca41e603c71f00966835503f84ef82db3e46dc439f7687f274113
bosscatrocketclub.org
https://pool.pm/asset1k3wfwk68zz24xl8k9pxfsa406l92zwd8e2xaw4

The APE Society Free Mint Key
34cf7d191ea1ec262a2d64ad75e69bc2e617ca8822708d9a076bf5e3
theapesociety.net
https://pool.pm/asset1hd8hmwac5733m8szmd9nea522nuuke5f9sc6z4

EQUINE NFT FREE MINT KEY
d97f34185f3d8ff166cb45b9a1b63aac6b0f6bcddaf87570d0587530
equinemint.org
https://pool.pm/asset1qs7gz9l9egl3cuu45sfnae2yvt0kpmna98sgv7

Chilled Kongs NFT Free Mint Key
c0697ca26948309303a268b18d50eee48b0cd2dd1b4377f3b61dea68
chilledkongsnft.com
https://pool.pm/asset1206ngesc70nx2nkxdnyr7xt844sxzhjssg4sg5

RISK REWARD TOKEN
ebe4407c271eb08ef0efe1eae595f8103d3716b93c0d4e2b2c6c386d
riskcoin.org
https://pool.pm/asset1smmcrcdnwvwg4azavm678e2rvl5gcyzcgfxhnj

SpaceBudz NFT Free mint key
5244c9979efa4d49159c01c91f00bd2e17e327258b5a169f60f60122
spacebudz.net
https://pool.pm/asset17jwadpk66q8zxk9z76rcg5y662yvuf0ztwxywa

NEWM BONUS TOKEN
8159b2c362b2107fa2dc9587a781feac4bc544e2c086544603625475
newm.top
https://pool.pm/asset14hxy0wkrmtunwa48tfl4hxr02apf99vw2ut4n6

Everstake Reward Token
dc2ac9b105bbfa44ceb9804b7e008e4e760bc6a9370305cabee01a69
everstake-reward.com
https://pool.pm/asset12x2fq0j22wxfhpg3479zc7sfhwllawmz5mdn9t

THE APE SOCIETY FREE MINT KEY
73b1c2a0d3a0ecf13fd1d30f34c3a5e23eb218afff68517784a8fca0
theapesociety.net
https://pool.pm/asset1ymftzdxe2z7mpuwpqpqf88yugk7rz8qwuxepvd

BossCat Rocket Club NFT Mint Key
4ad5e926991ae6e7250492d49d1fa63e8ec235d96f247a363e3fece8
bosscatrocketclub.org
https://pool.pm/asset1ecp33hx6fszju7zaakpy2u6f6gj40myayf7ffd

CLAY NATION NFT MINT KEY
6130d092a0eaeee3db354ce1c2df2ef38eb67d126edc64a4aad1c28b
claynationnft.com
https://pool.pm/asset1uxazlk727p39989rav3wegt9afywvgc92ld6jp

CLAP Rebranding Reward Token
b52139a43815fb07b493c17830aff2859d7137a460d71363abf90a43
erables.org
https://pool.pm/asset136ck2jma04crxattk40ld8ya0htd0z6yu7qv0t

PBX Reward V2
3983c54b32ddc202274656fb0a695357b44e303cda44528ee707b2c4
paribus-reward.com
https://pool.pm/asset10gds8tl72nnuzt62g5tulxm4v99f73pvm2w42z

MCOS Bonus Token
f7a663feebe9b06fd0cd204a3a2974074039ae317eb30a42f51eaeed
mocossi.org
https://pool.pm/asset1h8p4n5tmephq9rp3wz6djnlktq8qc30n883nrr

Genesis Hero
000dbe0b66e9ceb8357eeb7eacbdc6e2707345924ba86bf300d2ad8e
chainsofwar.org
https://pool.pm/asset1fq0hdsp2lsxymy78l9en5spv8vt0jyhzpqsqfs

**Comment by ThirdEye707** [comment]
Done

Thank you!

‫בתאריך יום ה׳, 1 בפבר׳ 2024 ב-7:07 מאת ‪bnchk‬‏ ***@***.***
‬‏>:‬
