### ISSUE TITLE
Scam Report - [NFT]

### ISSUE THREAD

**Issue by pbwebdev** [adabox-aio/cardano-shield#20]
## Scam Report 

**NFT Project**: Scam token airdrop

**Description of the Scam**:
Scam token airdropped to delegates telling them about a 5000 ADA event by going to the website. Website is a fake.

**Evidence**:
https://pool.pm/policy/5c9164aae7f5f634c89a58eda90e71df0325775361a931c56524670e

**Additional Information**:
takes you to a scam website adaozpool.com where you can connect your wallet and get scammed.

**Comment by hizkiya** [comment]
Added. Thanks
