### ISSUE TITLE
NFT Policy is not linked to scam URL and the lists are out of sync

### ISSUE THREAD

**Issue by bnchk** [adabox-aio/cardano-shield#9]
Hi there, noticed the data has lost the link between scam URL and NFT so created json that maintains the linkage.

Wallets would benefit from knowing URLs that are scam when doing initial authorisation check, and saw at least book.io scam sites were in NFT and not in domain lists.

The domain list could be extracted from this blacklist json really easily and there is only one place for data updates then.

But zero drama if not needed, just updated in case of use :-)

**Comment by adamcazes** [comment]
Thanks
we have updated the list to include a URL, with slight modifications
the policies, domains and stake addresses need to be separated within the file for efficiency
thanks for your contribution <3
